DROP TABLE IF EXISTS "detail" CASCADE;
DROP TABLE IF EXISTS "buyer" CASCADE;
DROP TABLE IF EXISTS "invoice" CASCADE;
DROP TABLE IF EXISTS "invoice_line" CASCADE;
DROP TABLE IF EXISTS "sale_history" CASCADE;
DROP TABLE IF EXISTS "price_history" CASCADE;
